#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_master.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define AUDIO_PDM_MIC_GPIO_SCK  GPIO_NUM_1
#define AUDIO_PDM_MIC_GPIO_DIN  GPIO_NUM_2
#define AUDIO_PDM_MIC_GPIO_WS   GPIO_NUM_42
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_4
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_6
#define AUDIO_MUTE_PIN          GPIO_NUM_7

#define TOUCH_I2C_CLK_HZ (400000)
#define TP_I2C_SCL_IO GPIO_NUM_18
#define TP_I2C_SDA_IO GPIO_NUM_17
#define TP_I2C_RST_IO GPIO_NUM_10
#define TP_I2C_INT_IO GPIO_NUM_9
#define TP_I2C_ADDRESS           (0x15)
#define TP_I2C_START_REG         (0x02)
#define TP_CHIP_ID_REG           (0xA7)

#define DISPLAY_WIDTH  472
#define DISPLAY_HEIGHT 466
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define QSPI_LCD_H_RES (472)
#define QSPI_LCD_V_RES (466)
#define QSPI_LCD_BIT_PER_PIXEL (16)

#define QSPI_LCD_HOST SPI2_HOST
#define QSPI_PIN_NUM_LCD_PCLK GPIO_NUM_48
#define QSPI_PIN_NUM_LCD_CS GPIO_NUM_12
#define QSPI_PIN_NUM_LCD_DATA0 GPIO_NUM_13
#define QSPI_PIN_NUM_LCD_DATA1 GPIO_NUM_47
#define QSPI_PIN_NUM_LCD_DATA2 GPIO_NUM_21
#define QSPI_PIN_NUM_LCD_DATA3 GPIO_NUM_14
#define QSPI_PIN_NUM_LCD_RST GPIO_NUM_11
#define QSPI_PIN_NUM_LCD_BL GPIO_NUM_45

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define TP_PORT (I2C_NUM_1)
#define TP_PIN_NUM_SDA (TP_I2C_SDA_IO)
#define TP_PIN_NUM_SCL (TP_I2C_SCL_IO)
#define TP_PIN_NUM_RST (TP_I2C_RST_IO)
#define TP_PIN_NUM_INT (TP_I2C_INT_IO)

#define DISPLAY_BACKLIGHT_PIN QSPI_PIN_NUM_LCD_BL
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define SDCARD_PIN_CMD GPIO_NUM_38
#define SDCARD_PIN_CLK GPIO_NUM_39
#define SDCARD_PIN_D0  GPIO_NUM_40
#define SDCARD_PIN_D1  GPIO_NUM_NC
#define SDCARD_PIN_D2  GPIO_NUM_NC
#define SDCARD_PIN_D3  GPIO_NUM_NC
#define SDCARD_PIN_CD  GPIO_NUM_41
#define MOUNT_POINT    "/sdcard"

#endif // _BOARD_CONFIG_H_
